use_frameworks!

platform :ios, '10.0'

target 'SKCollectionViewFlexLayout_Example' do
  pod 'SKCollectionViewFlexLayout', :path => '../'

  target 'SKCollectionViewFlexLayout_Tests' do
    inherit! :search_paths

    
  end
end
